# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxDataSourceExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxDataSourceExample
  pod 'RxDataSources'
  pod 'NSObject+Rx'

  target 'RxDataSourceExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxDataSourceExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
