# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxActionExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxActionExample
  pod 'Action'

  target 'RxActionExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxActionExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
